import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/dashboard/dashboardLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClientLayout>{children}</ClientLayout>
  );
}
